import { 
    Brain, Heart, Wallet, Dumbbell, Sparkles, 
    Target, PenLine, Zap, Activity, BarChart3, Cpu, TrendingUp
} from 'lucide-react'

const favicon = (domain: string) =>
    `https://www.google.com/s2/favicons?domain=${domain}&sz=64`

export const INTEGRATIONS = [
    {
        id: 'gmail',
        name: 'Gmail',
        brand: 'Google',
        logo: favicon('mail.google.com'),
        logoBg: 'bg-white',
        status: 'connected' as const,
        shortDesc: 'Email context & smart task extraction',
        usedFor: [
            'Surfaced as context in the AI Assistant',
            'Extracts tasks and reminders from incoming emails',
            'Provides deadline awareness from your inbox',
        ],
        moduleLink: '/intelligence',
        moduleLabel: 'Open Assistant',
    },
    {
        id: 'gdrive',
        name: 'Google Drive',
        brand: 'Google',
        logo: favicon('drive.google.com'),
        logoBg: 'bg-white',
        status: 'connected' as const,
        shortDesc: 'File access & document intelligence',
        usedFor: [
            'AI assistant can reference your documents',
            'Studio research and creative asset access',
            'Goal and project documentation context',
        ],
        moduleLink: '/intelligence',
        moduleLabel: 'Open Assistant',
    },
    {
        id: 'gemini',
        name: 'Gemini',
        brand: 'Google',
        logo: favicon('gemini.google.com'),
        logoBg: 'bg-white',
        status: 'connected' as const,
        shortDesc: 'Primary AI reasoning core & context processing',
        usedFor: [
            'Powers the personalised AI assistant persona',
            'Cross-module contextual reasoning and synthesis',
            'Routine generation, goal analysis & life optimisation',
        ],
        moduleLink: '/intelligence',
        moduleLabel: 'Open Assistant',
    },
    {
        id: 'openai',
        name: 'OpenAI',
        brand: 'OpenAI',
        logo: favicon('openai.com'),
        logoBg: 'bg-white',
        status: 'connected' as const,
        shortDesc: 'Content generation, cover art & AI suggestions',
        usedFor: [
            'Studio content title & description generation',
            'AI-generated cover images for projects and content',
            'Task AI suggestions and smart recommendations',
        ],
        moduleLink: '/create',
        moduleLabel: 'Open Studio',
    },
    {
        id: 'monzo',
        name: 'Monzo',
        brand: 'Monzo',
        logo: favicon('monzo.com'),
        logoBg: 'bg-white',
        status: 'connected' as const,
        shortDesc: 'Real-time banking, pots & transaction sync',
        usedFor: [
            'Live pot balances across personal & business profiles',
            'Auto-categorised transaction history with analytics',
            'Savings goals linked directly to pot balances',
        ],
        moduleLink: '/finances',
        moduleLabel: 'Open Finances',
    },
    {
        id: 'gymgroup',
        name: 'TheGymGroup',
        brand: 'TheGymGroup',
        logo: favicon('thegymgroup.com'),
        logoBg: 'bg-white',
        status: 'connected' as const,
        shortDesc: 'Gym proximity & fitness session context',
        usedFor: [
            'Nearest location tracking for session planning',
            'Fitness routine suggestions based on accessible gyms',
            'Workout context for the Wellbeing intelligence layer',
        ],
        moduleLink: '/health/fitness',
        moduleLabel: 'Open Wellbeing',
    },
    {
        id: 'framer',
        name: 'Framer',
        brand: 'Framer',
        logo: favicon('framer.com'),
        logoBg: 'bg-white',
        status: 'connected' as const,
        shortDesc: 'Website publishing & content sync pipeline',
        usedFor: [
            'Syncs Studio content to your live Framer website',
            'Publishes blog posts, portfolio items and press features',
            'Hashnode integration for developer articles',
        ],
        moduleLink: '/create',
        moduleLabel: 'Open Studio',
    },
    {
        id: 'x',
        name: 'X (Twitter)',
        brand: 'X Corp',
        logo: favicon('x.com'),
        logoBg: 'bg-black',
        status: 'connected' as const,
        shortDesc: 'Social distribution & content publishing',
        usedFor: [
            'Content publishing pipeline from Studio to X',
            'Audience engagement context for content strategy',
            'Platform reach metrics in Studio analytics',
        ],
        moduleLink: '/create/content',
        moduleLabel: 'Open Content',
    },
]

export const PHASES = [
    {
        id: 1,
        label: 'Phase I',
        title: 'Life OS Foundation',
        state: 'active' as const,
        year: '2024–2026',
        description: 'The core infrastructure is live. Every major facet of daily life is trackable, manageable, and beginning to connect through a shared AI intelligence layer.',
        items: [
            'Tasks, goals, operations & reminders',
            'Real-time financial tracking (Monzo + manual)',
            'Studio — projects, content, canvas, portfolio',
            'Wellbeing — fitness, nutrition, mental health',
            'Vault — encrypted notes & secrets management',
            'AI Assistant with deep personal context',
            'Daily Brief & Evening Debrief intelligence',
            'Cross-module data aggregation & trend analysis',
        ],
    },
    {
        id: 2,
        label: 'Phase II',
        title: 'Biometric Layer',
        state: 'pending' as const,
        year: '2026–2028',
        description: 'The next layer unlocks continuous physiological monitoring. By integrating with consumer wearables, Schrö gains a real-time picture of your physical state and adapts everything around it.',
        items: [
            'Apple Health / HealthKit continuous data',
            'Oura Ring — sleep stages, HRV, readiness score',
            'Garmin / Whoop — training load & recovery metrics',
            'Continuous glucose monitoring integration',
            'Cortisol & hormonal rhythm tracking',
            'Adaptive scheduling based on biometric state',
            'Sleep quality analysis & optimisation',
            'Correlating mood, performance & physiology',
        ],
    },
    {
        id: 3,
        label: 'Phase III',
        title: 'Neural Integration',
        state: 'future' as const,
        year: '2028+',
        description: 'When non-invasive BCI technology reaches consumer maturity, Schrö will integrate cognitive-state awareness to deliver truly adaptive, real-time life intelligence at a neurological level.',
        items: [
            'Brain-computer interface (BCI) integration',
            'Real-time cognitive load & focus state detection',
            'Emotional and stress state awareness',
            'Thought-assisted task creation',
            'Peak performance window prediction',
            'Mental fatigue early warning system',
            'Neural-adaptive environment and workflow control',
            'Direct feedback loops between thought and action',
        ],
    },
]

export const ROLES = [
    { icon: Brain,    label: 'Life Coach',       iconBg: 'bg-indigo-50',    iconColor: 'text-indigo-500',  desc: 'Guides your direction, builds habits, and holds you accountable to who you\'re becoming.' },
    { icon: Heart,    label: 'Therapist',         iconBg: 'bg-rose-50',      iconColor: 'text-rose-500',    desc: 'Tracks emotional patterns, surfaces mental health insights, helps you process your inner world.' },
    { icon: Dumbbell, label: 'Fitness Coach',     iconBg: 'bg-orange-50',    iconColor: 'text-orange-500',  desc: 'Designs adaptive training plans based on energy, recovery windows, and performance goals.' },
    { icon: Zap,      label: 'Nutritionist',      iconBg: 'bg-amber-50',     iconColor: 'text-amber-600',   desc: 'Optimises your nutrition based on goals, activity, physiological data, and what\'s in your fridge.' },
    { icon: Wallet,   label: 'Financial Advisor', iconBg: 'bg-emerald-50',   iconColor: 'text-emerald-600', desc: 'Tracks your wealth trajectory, spots waste, and guides every financial decision.' },
    { icon: PenLine,  label: 'Creative Mentor',   iconBg: 'bg-purple-50',    iconColor: 'text-purple-500',  desc: 'Elevates creative output, structures ideas into projects, connects them to your vision.' },
    { icon: Target,   label: 'Work Boss',         iconBg: 'bg-blue-50',      iconColor: 'text-blue-500',    desc: 'Prioritises your workload, manages deadlines, keeps you in peak execution during your best hours.' },
    { icon: Sparkles, label: 'Personal Oracle',   iconBg: 'bg-black/[0.04]', iconColor: 'text-black/60',   desc: 'The synthesis of everything — an intelligence that knows you holistically and guides you forward.' },
]

export const DATA_SOURCES = [
    { label: 'Tasks & Goals', icon: Target,    iconBg: 'bg-blue-50',      iconColor: 'text-blue-500'    },
    { label: 'Finances',      icon: BarChart3,  iconBg: 'bg-emerald-50',   iconColor: 'text-emerald-600' },
    { label: 'Wellbeing',     icon: Heart,      iconBg: 'bg-rose-50',      iconColor: 'text-rose-500'    },
    { label: 'Studio',        icon: PenLine,    iconBg: 'bg-orange-50',    iconColor: 'text-orange-500'  },
    { label: 'Operations',    icon: Activity,   iconBg: 'bg-indigo-50',    iconColor: 'text-indigo-500'  },
    { label: 'Biometrics',    icon: Cpu,        iconBg: 'bg-black/[0.04]', iconColor: 'text-black/25',   muted: true },
]
